### ISSUE TITLE
Implement minimal CTFTime scoreboard JSON format

### ISSUE THREAD

**Issue by dwendt** [isislab/CTFd#101]
For results, CTFTime is using this format:

https://ctftime.org/json-scoreboard-feed

/scores should try to match it. or maybe, /scores_ctftime

**Comment by ColdHeat** [comment]
Odd, I thought I had implemented this correctly. I'll fix it in a bit.

**Comment by ColdHeat** [comment]
I think overall it will be fine if I change `name` to `team`
