### ISSUE TITLE
Time confusion

### ISSUE THREAD

**Issue by dookgit** [isislab/CTFd#112]
Hey

When i view a submitted flag in the keys.log file i can see the following:

![flag](https://cloud.githubusercontent.com/assets/10006917/14837306/7e8b4f1c-0c5a-11e6-85f0-d72ff8143c3c.JPG)

Which is the correct time for the timezone set on my server.

But on the scoreboard the same flag submission time shows the following:

![flag2](https://cloud.githubusercontent.com/assets/10006917/14837332/abbace86-0c5a-11e6-8653-fc2a7c9d9a20.JPG)

So looks like the scoreboard is using UTC time? As opposed to the servers actual timezone?

Thanks.

**Comment by ColdHeat** [comment]
The scoreboard JavaScript should normalize the timestamp generated to your
local time zone.

I may need to do some testing but does the time not line up with what's
local to your computer?

**Comment by dookgit** [comment]
The time in the keys.log matches my servers time exactly (Timezone is UTC +10 AEST)

But yeah the time on the scoreboard doesn't match (mins and secs do) and looks like it's just reading the UTC time.

**Comment by dookgit** [comment]
Yup...just confirmed with another test account.   keys.log reports correct time for my servers time, but scoreboard shows UTC time.

**Comment by ColdHeat** [comment]
Which endpoint is this on?

**Comment by dookgit** [comment]
Err...sorry Endpoint?  As in which part of the scoreboard?  From the admin perspective, if i select Teams, and a specific team.  I can see when they submitted the flag

**Comment by ColdHeat** [comment]
Interesting bug. Not totally sure what's wrong but should be fixed now.

**Comment by dookgit** [comment]
Boom!  And confirmed fixed.

![flagfixed1](https://cloud.githubusercontent.com/assets/10006917/14840120/4d81c508-0c74-11e6-84b6-ee2415b06320.JPG)

![flagfixed2](https://cloud.githubusercontent.com/assets/10006917/14840121/51f3b8e4-0c74-11e6-87b8-fbd8ab3e81a6.JPG)


Legend!  Thanks Kevin :)
