### ISSUE TITLE
feature request: ctftime json live feed/export

### ISSUE THREAD

**Issue by crowell** [isislab/CTFd#115]
CTFtime.org requires ctf administrators to provide the scoreboards in a specific json format.

https://ctftime.org/json-scoreboard-feed

it would be great to have a button as an admin to export to json for ctftime.

"Also you can provide JSON feed of your CTF scoreboard, so we can update information at CTFtime in realtime. At the moment this feature is in progress." with an externally accessable json scoreboard would be cool too

**Comment by ColdHeat** [comment]
The /scores endpoint is configured to do this as per the minimal scoreboard
feed.

**Comment by crowell** [comment]
ok, didn't know that, closing :+1:
