### ISSUE TITLE
user ban

### ISSUE THREAD

**Issue by CingulateCortex** [isislab/CTFd#116]
hi 

if user is banned and during this time it is online, user is still able to see the challenge and answer the challenge as well.

**Comment by ColdHeat** [comment]
This is by design.

CSAW never removes a user from competing and thus CTFd only ever hides a
user.

If you feel strongly that it should be another way please say so.

**Comment by CingulateCortex** [comment]
this is related with approach i think. 

for example if i prepare a ctf and someone performing bad activity somehow, i would ban and remove username i guess. Actually dont want him to see the rest of the challenges.

**Comment by ColdHeat** [comment]
How would you prevent him creating another user? Aside from the situation
in which you have a limited user count CTF in which case you can simply
delete the user?
