### ISSUE TITLE
when i run serve.py

### ISSUE THREAD

**Issue by calistochen** [isislab/CTFd#119]
Traceback (most recent call last):
  File "./serve.py", line 2, in <module>
    app = create_app()
  File "/root/CTFd/CTFd/__init__.py", line 15, in create_app
    from CTFd.models import db, Teams, Solves, Challenges, WrongKeys, Keys, Tags, Files, Tracking
  File "/root/CTFd/CTFd/models.py", line 7, in <module>
    from passlib.hash import bcrypt_sha256
ImportError: cannot import name bcrypt_sha256

but i am sure that i had installed bcrypt

**Comment by ColdHeat** [comment]
I think there is sometimes an issue with the bcrypt backend installed. Perhaps try installing a different one or upgrading passlib?

**Comment by calistochen** [comment]
i am sure that i had upgraded the newest version

**Comment by calistochen** [comment]
pip list
argparse (1.2.1)
bcrypt (2.0.0)
cffi (0.8.6)
chardet (2.3.0)
colorama (0.3.2)
cryptography (0.6.1)
defusedxml (0.4.1)
Django (1.9.6)
django-hashers-passlib (0.3)
django-sha2 (0.4)
docutils (0.12)
Flask (0.10.1)
Flask-Passlib (0.1)
Flask-Session (0.2.3)
Flask-SQLAlchemy (2.1)
gunicorn (19.4.5)
html5lib (0.999)
itsdangerous (0.24)
Jinja2 (2.7.3)
lxml (3.4.0)
MarkupSafe (0.23)
ndg-httpsclient (0.3.2)
numpy (1.8.2)
passlib (1.6.1)
pexpect (3.2)
Pillow (2.6.1)
pip (1.5.6)
ply (3.4)
py-bcrypt (0.4)
pyasn1 (0.1.7)
pycparser (2.10)
pycups (1.9.63)
pycurl (7.19.5)
Pygments (2.0.1)
pygobject (3.14.0)
pyinotify (0.9.4)
PyMySQL (0.7.2)
pyOpenSSL (0.14)
pysmbc (1.0.15.3)
python-apt (0.9.3.12)
python-debian (0.1.27)
python-debianbts (1.11)
pyxdg (0.25)
reportbug (6.6.3)
reportlab (3.1.8)
requests (2.4.3)
roman (2.0.0)
setuptools (5.5.1)
sha256 (0.1)
six (1.8.0)
SOAPpy (0.12.22)
SQLAlchemy (1.0.12)
SQLAlchemy-Utils (0.32.5)
urllib3 (1.9.1)
Werkzeug (0.9.6)
wheel (0.24.0)
wsgiref (0.1.2)
wstools (0.4.3)

**Comment by calistochen** [comment]
anybody help？

**Comment by ColdHeat** [comment]
https://pythonhosted.org/passlib/lib/passlib.hash.bcrypt_sha256.html

You need to update to passlib 1.6.2. Run `pip install --upgrade passlib`
