### ISSUE TITLE
An important problem~ help me

### ISSUE THREAD

**Issue by Alex943297** [isislab/CTFd#122]
i want to know How to change the problems' color you had solved....
if there are many problems ,you will puzzled  which you had sloved and which hadn't.
 
 thanks a lot！

**Comment by ColdHeat** [comment]
Hi I believe you can change the color of solved challenge buttons by changing these CSS lines:

https://github.com/isislab/CTFd/blob/master/CTFd/static/css/style.css#L172-L174
