### ISSUE TITLE
Exception when displaying IP on Team Detail page in Admin Mode

### ISSUE THREAD

**Issue by snurilov** [isislab/CTFd#136]
When attempting to display a detailed view of a Team in the Admin Mode, if the first octet of the IP address is bigger than 127, an exception is generated. (e.g. 192.168.0.1)

This happens because the IP address is interpreted as an signed long and the call to inet_ntoa fails in the long2ip function in util.py.

**Comment by ColdHeat** [comment]
I think I know what the issue+fix is but can I get a stack trace just so I can be sure

**Comment by ColdHeat** [comment]
Not sure that's the best fix in this case as the issue is due to the conflict with the long2ip function in models.py

**Comment by ColdHeat** [comment]
Can you take a look at a4e51fcc761afea4a28ebe6968dfdab4dd04556c and make sure it fixes your issue?

**Comment by snurilov** [comment]
Looks like it fixed the issue.
