### ISSUE TITLE
Deployment Documentation or Script

### ISSUE THREAD

**Issue by student0123** [isislab/CTFd#14]
I don't believe there is a callable function that is compatible with Gunicorn or uWSGI.  I am launching uwsgi via the following command:
```
uwsgi --http-socket :80 -w CTFd:create_app
```
Then I navigate to http://127.0.0.1 and get the following error:
```
 File "./CTFd/__init__.py", line 20, in create_app
    SQLALCHEMY_DATABASE_URI = 'mysql://'+username+':'+password+'@localhost:3306/' + subdomain + '_ctfd',
TypeError: cannot concatenate 'str' and 'builtin_function_or_method' objects
```
Everything works fine when letting Flasks internal handler serve http.

**Comment by takeshixx** [comment]
I guess uWSGI overrides the `create_app()` parameters and tries to concatenate them with the rest of the mysql-URI. Change the following line in `__init__.py`:

```
def create_app(subdomain, username="", password=""):
```

to:

```
def create_app(subdomain, username="", password="",  *args, **kwargs):
```

And try it again. If that fixes the uWSGI incompatibility, feel free to create a pull request for this.

**Comment by ColdHeat** [comment]
Interesting problem, I've never deployed with uwsgi before but I'll look into it.

**Comment by Charg** [comment]
To work around the issue I'm running gunicorn as follows:

> gunicorn -b 0.0.0.0:8080 "CTFd:create_app('')"

Running gunicorn without parameters in the `create_app()` function results in

```
subdomain: <type 'dict'>
username: <type 'instancemethod'>
password:<type 'str'>
```

**Comment by ColdHeat** [comment]
This should really just be resolved with `subdomain=""` in create_app.

**Comment by ColdHeat** [comment]
So deploying with uWSGI is a major headache but `uwsgi --http-socket :80 -w CTFd:create_app()` will work. I'm going to close this and open a new issue discussing documentation.
