### ISSUE TITLE
Broken CSRF check when installing

### ISSUE THREAD

**Issue by nashe** [isislab/CTFd#148]
Aloha,

First of all, thanks for this project :-)

When I'm submitting the configuration form on a clean instance of CTFd, I get a 403. I found that the only part of the code which could throw this error is related CSRF mitigation. The quick (hideous) fix is to remove this CSRF check. The token (`nonce`) is in the form but I guess that the value in the session is not the right one.

I don't have much time to dig into it, so I'm just reporting it for now. I'll try to do a proper PR if nobody does.

*Steps to reproduce*:
- (I added `ports: - 8000:8000` in the `docker-compose.yml`)
- `docker-compose up`
- Go to http://localhost:8000
- Fill the form, click on "Submit"
- A 403 is shown.

**Comment by ColdHeat** [comment]
I'm unable to reproduce...

Can you try this again?

**Comment by nashe** [comment]
After the third trial, it's not happening anymore. I have other errors but it's working, sorry for the waste of time ;-(

By example, in `docker-compose-run.sh`, [this line](https://github.com/isislab/CTFd/blob/master/docker-compose-run.sh#L7) looks weird, since `i` is never declared. Submitting a PR for this.
