### ISSUE TITLE
Demo website oddity

### ISSUE THREAD

**Issue by MarioVilas** [isislab/CTFd#159]
When I try to go to http://demo.ctfd.io/ it redirects me to https://stories.haurwitz.com/ instead. No idea why. The SSL certificate also matches stories.haurwitz.com instead of demo.ctfd.io.

I know it's not a big deal, but maybe you didn't notice and it's kinda annoying.

**Comment by ColdHeat** [comment]
Hey thanks! This is actually because I forgot to update the DNS rule after killing a DigitalOcean Droplet and the IP address must've gotten recycled. 

Thanks for the heads up!

**Comment by ColdHeat** [comment]
Updated DNS rules and it's just a matter of time now :)
