### ISSUE TITLE
Question regarding pages / blank pages.

### ISSUE THREAD

**Issue by balonfx** [isislab/CTFd#161]
We're attempting to test loads on the website. We need to be able to create an entire blank page, but the header keeps getting attached. While we have a fair amount of experience in css/php/html/js, python isn't of our skills so we're not sure how the header is being attached to each page.

Understanding this will allow us to attach a footer across the website as well.

**Comment by ColdHeat** [comment]
The pages feature isn't meant to create blank pages. It's more meant to create HTML content as part of the overall CTF site. 

If you want to create a purely blank page you're going to want to edit 
https://github.com/isislab/CTFd/blob/master/CTFd/templates/original/page.html

as it is the base file where HTML is inserted.

**Comment by balonfx** [comment]
If I wanted to make just one blank page, is this something I'd change in python? We just want one called loader.txt. But if we create it in the directory, won't load.. if we create it in pages, has the header.

We want every other page to have the header of course.

**Comment by ColdHeat** [comment]
You can add something like this to CTFd/views.py for a completely blank page. 

```python
@views.route("/loader.txt")
def blank():
    return ""
```

**Comment by balonfx** [comment]
Thank you very much.

👍

**Comment by balonfx** [comment]
One last question on this: 

If I wanted to return say an HTML file, instead of the text in return "", that is in the same directory as the serve.py.. what would be the most efficient way of doing this? (So if I had a file like loader.txt in this directory, I could return the contents of it, and if it's .html, return the contents of that.)


Thanks.
