### ISSUE TITLE
UTF-8 keys

### ISSUE THREAD

**Issue by sk13** [isislab/CTFd#164]
It seems that submitting UTF-8 keys ist broken.
More specifically the line 184 in challenges.py

`key = str(request.form['key'].strip().lower())`

seems to lead to an HTTP 500.
Changing this line to:

`key = unicode(request.form['key'].strip().lower())`

seems to fix the problem - but I do not know what are the side effects.

**Comment by ColdHeat** [comment]
Thanks, will look into this.
