### ISSUE TITLE
Unable to delete Awards

### ISSUE THREAD

**Issue by dookgit** [isislab/CTFd#173]
If you give a team an award, and then you want to delete it from their page through the admin page, you can't,

When i click the X next to delete, in my browser Console it shows:

ReferenceError: chal is not defined

Guessing the deletion stuff was brought across from challenges page, and that reference remains.

Cheers

**Comment by ColdHeat** [comment]
This bug sounds like it's from an older commit. 

Is your CTFd instance recent? For now until the versioning is in, you'll probably need to keep pulling from master.

**Comment by dookgit** [comment]
I haven't to be honest, let me pull a fresh one and confirm.  Sorry.

**Comment by dookgit** [comment]
Yup, confirmed, works in latest commit. My bad :)
