### ISSUE TITLE
AWS ELB with nginx config please?

### ISSUE THREAD

**Issue by vtknightmare** [isislab/CTFd#175]
Hi There:

So I've been bashing my head against the wall, and would appreciate a hand with the nginx and CTFd config parameters needed, such that when I push the CTFd and nginx docker containers to the AWS ECR, and terminate the connection behind an ELB it would serve over HTTPS only. Currently I only get it to route over HTTP and am confused beyond belief at this point. The docker-compose refers to the dockerfile which uses gunicorn, which I'm fine with. I'm just trying to figure out how to get this sucker to run on HTTPS only.

I will be more than happy to pay forward in beers :)

Thank you,

**Comment by ColdHeat** [comment]
Hmm I'm not sure what you're asking. Are you terminating SSL at the ELB or are you looking to have the nginx docker container terminate SSL? 

This gist shows the nginx config which should be ok, you just need to link everything up with the right hostnames, ports, and files:
https://gist.github.com/yosemitebandit/1252240#file-yupyupnope-conf-L13-L37

**Comment by vtknightmare** [comment]
>> Are you terminating SSL at the ELB

Yep. What's happening is I have the nginx container listening on 80:80 to
add the http_proto_forwarded tags yet and then to do the re-write, but for
some reason, it's not doing the re-write peace, as a result it ends up
responding on port 80 back.

The gist you provided is for terminating at nginx which is not what I want.
Essentially I just wanto to deploy CTFd on AWS as a task with a service so
I can auto scale as needed using mariadb from RDS.

On Dec 7, 2016 5:29 PM, "Kevin Chung" <notifications@github.com> wrote:

Hmm I'm not sure what you're asking. Are you terminating SSL at the ELB or
are you looking to have the nginx docker container terminate SSL?

This gist shows the nginx config which should be ok, you just need to link
everything up with the right hostnames, ports, and files:
https://gist.github.com/yosemitebandit/1252240#file-yupyupnope-conf-L13-L37

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/isislab/CTFd/issues/175#issuecomment-265594138>, or mute
the thread

**Comment by ColdHeat** [comment]
Right you can cut out the SSL stuff from that nginx config and use it. But effectively it proxies out to the gunicorn instance and then the response goes up to nginx. 

I'm not sure what you mean by rewrite here. You have SSL terminating at the ELB so then the request should come from the ELB  and then go to the port you specified which in this case would be nginx over HTTP. nginx proxies to the app and then the response is served back by nginx.
