### ISSUE TITLE
How to Add New Field on Form Challenges?

### ISSUE THREAD

**Issue by seweithotroyman** [isislab/CTFd#176]
Hi there..

I want to add a column in the form of challenges. For example I added a column level. How can I add it? until the database is also available at the column level.

this screenshot for template >> [screenshot](http://image.prntscr.com/image/ec9346f052a34b8bb8663ff1429a52ef.png)

I've changed the template code, but I do not know how to change the python code in admin.py & model.py

already tried adding some code, but there is an error unresolved until today.

**Comment by ColdHeat** [comment]
You just need to look at models.py and look at the database schema. You'll need to understand SQLAlchemy in order to make that modification but it's fairly simply to look at what's already there and modify it.
