### ISSUE TITLE
Change Front Page Content

### ISSUE THREAD

**Issue by vtknightmare** [isislab/CTFd#177]
Hello,

After crawling through all the files, I noticed views.py has an entry on line :56 where it generates the initial content for the index/front page. I've changed the file content to suit my needs, yet the page rendering is the same old "cool CTF framework"

Can you point me to where I need to modify?

Thanks,

**Comment by ColdHeat** [comment]
I'm not sure what issue you're raising here. It is possible to change that content from the admin panel.

**Comment by ColdHeat** [comment]
Sorry your initial comment didn't really have a question. 

You can go to `/admin/pages` to edit the front page :)

**Comment by vtknightmare** [comment]
Oh, I want to add additional branding. We have in mind to modify the front page such that it says: "based on Kevin's awesome CTFd framework" on the bottom left then our competition logo etc will be front and center

**Comment by ColdHeat** [comment]
Right all of that is edittable from either the templates folder or from within the Pages functionality. 

Pages isn't very well fleshed out so I would probably create templates and modify [base.html](https://github.com/isislab/CTFd/blob/master/CTFd/templates/original/base.html#L35-L40)

**Comment by vtknightmare** [comment]
Cool! Thanks :)
