### ISSUE TITLE
Max Upload Size?

### ISSUE THREAD

**Issue by vtknightmare** [isislab/CTFd#178]
Hi Kevin et al

I just wanted to ask how can we tweak the current max size allowed for uploads? We tried to upload a pcap file (which as you know can get quite big) and after the upload seemingly completed it gave an 513 file too big error.

I perused the files for a setting, but couldn't locate any. I then saw the s3 plugin, but before I delve down that road wanted to see if there was a way to tweak the filesize upload limit.

Thanks,

**Comment by ColdHeat** [comment]
Hey @vtknightmare this is likely an nginx issue. 

Take a look at this: https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/

CTFd doesn't set Flask's MAX_CONTENT_LENGTH setting but perhaps you need that information: http://flask.pocoo.org/docs/0.11/patterns/fileuploads/#improving-uploads

**Comment by vtknightmare** [comment]
Thank you Kevin,

So after your post, I added the "client_max_body_size          0;" parameter to the nginx config and bounced the task, now noone can login.

We get the following message: "I don't think you're allowed here Not so sorry about that"

What could have broken by implementing the key in question?

**Comment by ColdHeat** [comment]
That message is specifically when Flask generates a 403 which is almost always due to CSRF nonce issues. 

Is your SESSION_KEY set to something random or a static value or is it default?

**Comment by vtknightmare** [comment]
I haven't modified or added any setting/code related to SESSION_KEY. It's whatever the default you provide is

**Comment by ColdHeat** [comment]
Well first I would try reverting your nginx change to see if that fixes things. I would probably just set it to something large instead of trying to get it to disable all checks for now.

**Comment by vtknightmare** [comment]
In fact I just wrapped up trying that, and yes, setting it to 1028M seems to have worked. Weeeiiirrrdd... no?

**Comment by ColdHeat** [comment]
Perhaps you are using an old version of nginx where the concept of 0 disabling the checking doesn't exist. 

¯\_(ツ)_/¯

If this is all fixed up for you can you close? 

Also if you want a somewhat faster resolution instead of the back and forth you can try joining https://slack.ctfd.io

**Comment by vtknightmare** [comment]
Yes it is, and joining it now! :)
