### ISSUE TITLE
Challenges containers

### ISSUE THREAD

**Issue by Hyooni** [isislab/CTFd#186]
Hello everyone,

Me and my team are currently using CTFd in order to make our own CTF, and we are having some problems with using the "Container" function to upload our challenges.

When creating a new container, we fill the title and dockerfile fields, and upload a file (BTW is it normal that you can't upload more than one file ?), but nothing appear on the container's list ... 

So my question is, how do you use the container function ?

PS : i'm using the last git version, and docker is installed on my server

**Comment by ColdHeat** [comment]
Hi Hyooni, the containers functionality is very much in beta but it should have worked if you simply were creating a docker container. 

If possible can you give me a stack trace or perhaps the dockerfile you entered in? 

Also you can upload multiple files, just select multiple files with Ctrl or Cmd when you open the file dialog.

**Comment by Hyooni** [comment]
Thanks for the fast reply, here is the Dockerfile we've been trying to use, a really simple one for starter : 

`FROM debian:jessie`

I've tried this directly on the server with `docker build .` and being on the same folder as my Dockerfile.
The command `docker images` shows the docker being up, and a `docker run -it debian:jessie` run effectively the docker.

Oh and thanks for the multiple files upload, but my problem is that the application developed have files and folders with files in it, and you can't seem to include folder+files with the Ctrl + clic method.

**Comment by ColdHeat** [comment]
@Hyooni It looks like this is a bug with CTFd thinking the name is invalid. 

Change [this line](https://github.com/isislab/CTFd/blob/master/CTFd/admin.py#L277)
 to the following:
`if not set(name) <= set('abcdefghijklmnopqrstuvwxyz0123456789-_'):`

I'll be patching this in master in a moment but just to get something for you immediately.
