### ISSUE TITLE
Template not found

### ISSUE THREAD

**Issue by kuskumar** [isislab/CTFd#194]
Hi Team,

I am getting following error when trying to browse CTF through browser.  Please help me out here.
<img width="706" alt="capture" src="https://cloud.githubusercontent.com/assets/7838777/22109499/052b7e3e-de7e-11e6-9168-283950cebd00.PNG">

**Comment by ColdHeat** [comment]
Hi @kuskumar sorry about the delayed response. I'm not able to reproduce, can you give me some more details about your setup? Did you delete the templates folder by accident perhaps? 

You can join us over at [Slack](https://ctfdio.slack.com) for a faster response.

**Comment by kuskumar** [comment]
Hi @ColdHeat 
Seems like Template folder didn't get cloned while cloning the project. It is working now. Thanks.

**Comment by ColdHeat** [comment]
👍
