### ISSUE TITLE
Email verification error

### ISSUE THREAD

**Issue by eilc0** [isislab/CTFd#203]
Hi 
I've got an error each time a user try to validate their email by the link sent by email ; 

any idea please ?

thank you.

![email_verification](https://cloud.githubusercontent.com/assets/12251888/22784875/14ab0a5a-eed2-11e6-8e8c-a26898bd81da.png)

**Comment by ColdHeat** [comment]
This was fixed recently by a pull request but the fix is in the testing
branch and not available in master yet.

See here https://github.com/isislab/CTFd/pull/202 for the patch.

**Comment by ColdHeat** [comment]
This is fixed in master now.
