### ISSUE TITLE
Teams can only have http (no s) websites

### ISSUE THREAD

**Issue by eugenekolo** [isislab/CTFd#210]
Particularly annoying, cause it passes the form validation, but the template filters it out. So it looks like it worked, but the website just shows up as nothing on the view.

https://github.com/isislab/CTFd/blob/master/CTFd/templates/original/teams.html#L26

```
<td>{% if team.website and team.website.startswith('http://') %}<a href="{{ team.website }}">{{ team.website }}</a>{% endif %}</td>
```

Kind of a silly filter, but can fix it with:

```
<td>{% if team.website and (team.website.startswith('http://') or team.website.startswith('https://')) %}<a href="{{ team.website }}">{{ team.website }}</a>{% endif %}</td>
```

**Comment by ColdHeat** [comment]
There is an open PR for this, I just haven't gotten to merging it in. 

Sorry about that, it'll happen later today with a bunch of code coming from the testing branch.

**Comment by eugenekolo** [comment]
Mb. I'll close.

**Comment by ColdHeat** [comment]
I have a feeling this is for BostonKeyParty? 

You may want to also take a look at this issue: https://github.com/isislab/CTFd/issues/203 if you are confirming emails.

**Comment by eugenekolo** [comment]
I noticed it on BKP, but I don't work on the website. I forwarded it to people who do. Thanks!
