### ISSUE TITLE
Challenge create sub-domain render bug

### ISSUE THREAD

**Issue by kevinschoonover** [isislab/CTFd#213]
## Problem Description
In the [standard-challenge-create.hbs](https://github.com/isislab/CTFd/blob/master/CTFd/static/admin/js/templates/challenges/standard/standard-challenge-create.hbs) file that is rendered in the ```/admin/chal/new``` route via the ```load_chal_template()``` function in [/chals/create.html](https://github.com/isislab/CTFd/blob/master/CTFd/templates/admin/chals/create.html) file, the jinja tags on line 2 will not render with a deployed sub-domain CTF.

For example, the CTF test instance I am currently running is using a /ctf/ subdomain and every link works except for this POST form method.

I am not all to familiar with out Flask utilizes jinja for rendering otherwise I would try to submit a pull request. I will continue to look into this issue, I just wanted to report this bug.

## Bug Verifcation
I attempted to add two tags to the [standard-challenge-create.hbs](https://github.com/isislab/CTFd/blob/master/CTFd/static/admin/js/templates/challenges/standard/standard-challenge-create.hbs) file in the following way:
```html
<div class="col-md-6 col-md-offset-3">
     <h2> Test {{ request.script_root }} </h2>
     <h2> {{ request.script_root }} </h2>
    <form method="POST" action="{{ request.script_root }}/admin/chal/new" enctype="multipart/form-data">
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" name="name" placeholder="Enter challenge name">
        </div>

...
```

In both scenarios, ```{{ request.script_root }}``` did not show on the page as '/ctf', they were blank.

Let me know if you require additional data.

**Comment by ColdHeat** [comment]
To clarify you're using the folder `/ctf` right? Not the subdomain `ctf.` ?

**Comment by ColdHeat** [comment]
Assuming it's the folder case I believe I understand the bug and will have a fix for it later today assuming I can get the right values into Handlebars.

**Comment by kevinschoonover** [comment]
Sorry, yes I am using /ctf/ not ctf.

**Comment by ColdHeat** [comment]
Hey just fixed this. 

I don't normally use CTFd in a subdomain so could you do a `git pull` and see if it's fixed for you?

**Comment by kevinschoonover** [comment]
It solved the issue. Thanks for the quick response.
