### ISSUE TITLE
New Design

### ISSUE THREAD

**Issue by ColdHeat** [isislab/CTFd#23]
The default Foundation look is pretty drab. A design overhaul would be great.

**Comment by crc442** [comment]
I can help. Do you have anything in mind for the new design?

**Comment by ColdHeat** [comment]
Nothing in mind but it really just needs something more than default Foundation. CSAW colors are here ![](http://i.imgur.com/DU9ZWxG.png) if you'd like to follow some kind of color scheme. 

I have very little design sense so would be super interested in anything you can come up with!
