### ISSUE TITLE
compilation fails with ./prepare.sh

### ISSUE THREAD

**Issue by AlfaroM** [isislab/CTFd#33]
http://imgur.com/It3tCxd

compliation fails due to lack of <ffi.h>

I'm not sure how to fix

**Comment by AlfaroM** [comment]
![capture](https://cloud.githubusercontent.com/assets/5588086/6957000/17c9cbb6-d8c4-11e4-8cba-d2806dee9621.PNG)

very sorry, didn't see you could attach images

**Comment by AlfaroM** [comment]
Nevermind, closing issue.

Solution: 
[code] apt-get install python-cffi[/code]

**Comment by bburky** [comment]
#30 should fix this.

For now, you can just `apt-get install libffi-dev`.
