### ISSUE TITLE
Interface to delete solves

### ISSUE THREAD

**Issue by ColdHeat** [isislab/CTFd#36]
Interface to delete solves

**Comment by slinkymanbyday** [comment]
Would be better if the successful keys were stored. Since keys can be regex, would be good to know what the submitted key actually was.

**Comment by ColdHeat** [comment]
I agree, I'll make some changes to `models.py` when I can. I also believe that it's better to store keys as a JSON blob in the Challenges table. Migration will probably be a pain...

**Comment by ColdHeat** [comment]
Closed in 44d1ea300bbde367d3fe90b5281ce13c005ff378
