### ISSUE TITLE
Limit displaying challenges?

### ISSUE THREAD

**Issue by jaredestroud** [isislab/CTFd#45]
After 10 challenges are present, the challenge page won't allow any competitor to click any available links to submit flags. Additionally,  several challenges are no longer being displayed all together. However, after deleting the 10th entry from the challenge table in the SQLite database everything goes back to normal.

Any idea on why this may be occurring?

**Comment by ColdHeat** [comment]
Perhaps the challenge is embedding some broken HTML into the page?

**Comment by jaredestroud** [comment]
Doesn't appear that way on my end.

**Comment by ColdHeat** [comment]
Sorry I got sidetracked. Do you think you can provide me with a dump of the database or similar so I can debug?

**Comment by jaredestroud** [comment]
The error occurred when  I created a new category for challenges, but did not immediately add a challenge to that category. It effectively "froze" any addition of new challenges. Removing this category from the sqlite database and then re-adding it with a challenge fixed this.
