### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by ColdHeat** [isislab/CTFd#51]
A docker container would make deployment easier

**Comment by JTWorks** [comment]
Just a basic Dockerfile that pulls your repo and runs serve.py with default configuration. 

https://github.com/UMBCCyberDawgs/DockerFiles/tree/master/CTFd

**Comment by ColdHeat** [comment]
Thank you very much! I'm going to use this as a baseline for a more production ready deploy (uwsgi or gunicorn) and test it out. 

Or if you set that up I'd totally accept a PR!
