### ISSUE TITLE
attached file problem.

### ISSUE THREAD

**Issue by hdarwin** [isislab/CTFd#54]
I attached challenge binary and tried to download it but I got this message
```
# client
Whoops, looks like we can't find that.
Sorry about that

# server
[pid: 2443|app: 0|req: 42/42] 39.124.110.87 () {36 vars in 1338 bytes} [Tue Sep 22 20:54:50 2015] GET /static/uploads/c9cccd1c00fc948e5f76acba9813878e/prob1 => generated 2939 bytes in 11 msecs (HTTP/1.1 404) 3 headers in 203 bytes (1 switches on core 0)
```
I ran server by this command 'uwsgi --http-socket :31337 -w "CTFd:create_app()"'  
what is the matter?!?!  
there is no downloadable attached file for any challenge. :(

**Comment by ColdHeat** [comment]
Will have a fix later today.
