### ISSUE TITLE
File upload for challenge not accessible

### ISSUE THREAD

**Issue by TobalJackson** [isislab/CTFd#59]
It seems that after deploying the server using a fresh clone and default settings that uploading a file results in the file being uploaded properly, but when going to access the file by the embedded link in the challenge text, the URL generates as: 
http://ctfdomain:4000/<sha-1 hash>/file.ext

and clicking on this link returns a 404 and the "Whoops, looks like we can't find that.  Sorry about that" page.

**Comment by ColdHeat** [comment]
Can you upload the associated sqlite database that's generated?

**Comment by ColdHeat** [comment]
Never mind I see the issue, thanks for the heads up
