### ISSUE TITLE
Issue with Gunicorn workers

### ISSUE THREAD

**Issue by ColdHeat** [isislab/CTFd#65]
Too many gunicorn workers. Need some way to share the secret key amongst workers or have less workers.

**Comment by aeibrahim** [comment]
I was trying to figure out why when I set gunicorn workers to 2 or more, I would not be login properly and then I saw this issue. Temporary fix is to run gunicorn with only a single worker.

**Comment by ColdHeat** [comment]
I actually didn't realize this was an explicit issue. 

I've resolved it in 81345dc6d2ca774ae92e01dd4a6658cafbd8b532 by writing a secret key to the .ctfd_secret_key file. The gunicorn workers will look for the file before generating a new key. 

This won't work with multiple servers but it works for most setups.
