### ISSUE TITLE
Running CTFd with 4 gunicorn workers (not just 1) blocks entering the admin views.

### ISSUE THREAD

**Issue by jaredmichaelsmith** [isislab/CTFd#68]
By running CTFd with 4 gunicorn workers (I suspect its just running it with more than 1), when trying to log in as the admin user it keeps returning me back to the login view.

The specific gunicorn command I am running it with is:
`gunicorn --bind 0.0.0.0:8000 --pid /home/ctfd/gunicorn.pid -w 4 "CTFd:create_app()"`

**Comment by ColdHeat** [comment]
There is currently an issue with gunicorn workers. Keep the worker amount to 1 while the bug gets figured out.

**Comment by jaredmichaelsmith** [comment]
Okay. Thanks!

**Comment by ColdHeat** [comment]
An alternative is to set the SECRET_KEY in config.py to a random and secret value. This is arguably the better solution but commiting something static into the repo would lead to bad things.
