### ISSUE TITLE
c3.js is outdated and breaks the scoreboard chart

### ISSUE THREAD

**Issue by jaredmichaelsmith** [isislab/CTFd#69]
Version 0.4.0 of c3.js pulled from cloudflare in scoreboard.html breaks the scoreboard with this error (as taken from Chrome Dev Tools):

`Failed to execute 'querySelectorAll' on 'Element': '.c3-selected-circles-[0]-TEAM_NAME' is not a valid selector.`

The issue in c3.js for this exact problem is here: https://github.com/masayuki0812/c3/issues/711

The fix for me was pulling the latest c3.js, version 0.4.1 from Github and updating the references in scoreboard.html.

**Comment by ColdHeat** [comment]
I believe this occurs under certain team names. When I encountered it I just constrained the team names to some chars. But I can update the files used from cdnjs.

**Comment by ColdHeat** [comment]
I intend to move to [plot.ly](https://plot.ly/javascript/) but I will update the cdnjs links today
