### ISSUE TITLE
Forgot password not working?

### ISSUE THREAD

**Issue by Nguyen-Dang-Thu** [isislab/CTFd#71]
Forgot password function not working. This is config file:
ADMINS = ['xxxxxxxx']

##### EMAIL (if not using Mailgun) #####
CTF_NAME = 'KMA'
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_PORT = 465
MAIL_USE_TLS = False
MAIL_USE_SSL = True
MAIL_USERNAME = 'xxxxxxxxx'
MAIL_PASSWORD = 'yyyyyyyyy'

What wrong? And how to fix it?
Tks!

**Comment by ColdHeat** [comment]
I feel like this might have been an issue with using Google SMTP servers versus CTFd. If you can give me a stack trace or something or something else actionable I'll gladly take a look into it. Try TLS perhaps?
