### ISSUE TITLE
CTF Start/Finish Times

### ISSUE THREAD

**Issue by dookgit** [isislab/CTFd#75]
I'm not sure how the Start Date/End Date functions work.

I've tried a few date/time formats And as soon as i enter something and click "Update" they disappear.

How can i tell if they have applied?

Is that any chance of a "Start CTF" and "Stop CTF" buttons in the Admin console? So we could do it manually.

Cheers

**Comment by ColdHeat** [comment]
Well they're supposed to be UTC time stamps as it says right here: https://github.com/isislab/CTFd/blob/master/CTFd/templates/admin/config.html#L27

But I agree that this needs to be changed. Users should be able to enter in regular times.

You can use this [site](http://www.epochconverter.com/) to convert regular time to a timestamp.

**Comment by dookgit** [comment]
Aha, awesome.  Wondered where i was going wrong :)  Thanks
