### ISSUE TITLE
CTFd with no internet connection - Missing css

### ISSUE THREAD

**Issue by dookgit** [isislab/CTFd#77]
I'm gonna be using CTFd for a CTF on a local network, but there will be no internet access available on the network. (People might have their own via tethering etc)

I've noticed when accessing CTFd without an internet connect, the layout is missing parts etc.  Is this due to some of the css files based online?

e.g - 
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/foundation/5.4.7/css/foundation.min.css" />
<link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" />
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/8.3/styles/railscasts.min.css">

See below screenshots of with/without internet access

![cc-styles-working](https://cloud.githubusercontent.com/assets/10006917/12692321/205eb0a4-c741-11e5-9627-9e55b43d5b41.JPG)
![cc-styles](https://cloud.githubusercontent.com/assets/10006917/12692322/2074b976-c741-11e5-9c53-a78759a8b958.JPG)

Am i able to download the required css files, and host locally, then modify the html pages in /templates to point to their new location, should that work nicer without any available internet?

**Comment by ColdHeat** [comment]
Yeah I don't have the JS/CSS files saved locally so as not to clutter the repository. Take a look at [issue 76])https://github.com/isislab/CTFd/issues/76)
