### ISSUE TITLE
Feature Scoreboard Auto Refresh

### ISSUE THREAD

**Issue by zeroSteiner** [isislab/CTFd#8]
It would be a nice feature if the scoreboard page could include some javascript to automatically refresh the data at a standard interval.

**Comment by zeroSteiner** [comment]
My mistake, it looks like this is already implemented and I just wasn't waiting long enough.

**Comment by ColdHeat** [comment]
This is implemented but it would probably be nice to do it with websockets. 

Flask just has a hard time with websockets so I'm not sure if I'll implement it or not.
