### ISSUE TITLE
Scoreboard appearance not uniform

### ISSUE THREAD

**Issue by p4tchw0rk** [isislab/CTFd#81]
The updated skin looks great, but the box sizes on the Scoreboard page are no longer uniform (size is title-length dependent). Category titles that are too long get cut off by the boxes as well ("Cryptography" in my case). The scoreboard page under Admin options is uniform (titles get cut off, but I think for the sake of aesthetics, the uniformity is cleaner). Great project. Thanks for your hard work.

**Comment by ColdHeat** [comment]
Are you sure you're not referring to the Challenges page? 

Also a screenshot could help with debugging aesthetics based things, could you provide one?

**Comment by ColdHeat** [comment]
Ehh nevermind, I see the issue :)

**Comment by p4tchw0rk** [comment]
My mistake. You are correct. It is the challenges page. Sorry for the confusion.
