### ISSUE TITLE
View board / or view remaining challenges for teams

### ISSUE THREAD

**Issue by jhaddix** [isislab/CTFd#82]
Hey ColdHeat! 

CTFd is awesome, thanks so much! It enabled me to run a intro-to-ctfs-CTF for my team. They loved it. One thing, as an admin, i was wondering if there could be a better way to see the progress of a specific team. Like see their challenges view or a list of not-solved challenges. As the competitions go longer, it would just help the admin know what challenges are commonly being avoided. This is turn would let me give clues or support, etc.

**Comment by ColdHeat** [comment]
Points is the usual metric for this but I don't see why there can't be a challenge completed count or similar.

**Comment by ColdHeat** [comment]
Some ideas are to:
* show which challenges a team has not solved in the admin team page. 
* In the admin challenge page show a percentage of completion meaning of all teams containing points what percentage have solved this challenge. 

I'll see if I can implement later today. 

As a sidenote, would it be ok to list Bugcrowd as a user of CTFd?

**Comment by jhaddix** [comment]
Both would be useful, and yes! Also, do you need any sponsorship for the platform?

**Comment by ColdHeat** [comment]
Awesome! 

And sponsorship would be super cool too! Any kind of assistance is appreciated but do you have something in mind? 

If you prefer you can email me at kchung@nyu.edu
