### ISSUE TITLE
Ability to manually modify scores

### ISSUE THREAD

**Issue by cwtaylor** [isislab/CTFd#84]
We have run only a single CTF with the platform so apologies if I am speaking garble :smiley: 

During the course of the competition there was some issues with the questions that meant answers were not being accepted and thus users being shut out of the questions. It would have been really useful if we could have modified the users score manually through the admin interface or reset their attempts manually.

There is also a use case where we might want to award teams additional points for certain things (such as a really interesting method) that could be in scope for this request.

Thanks anyway for reading this and making a great CTF platform.

**Comment by ColdHeat** [comment]
I think resetting attempts is doable by allowing an interface to delete wrong key submissions. There should be a route to do this but I will improve the UI for it and add it if it isn't already implemented. 

As for awarding additional points it will likely be a little tricky as CTFd calculates scores based off of the Challenge value. 

The best approach might be to create a new table which is taken into account on top of score...

**Comment by cwtaylor** [comment]
Thanks that sounds great. The additional score is low priority if we can remove incorrect answers. It is an edge request that is only needed if the challenge is not setup correctly.

**Comment by ColdHeat** [comment]
You can delete wrong keys and solves since commit 44d1ea300bbde367d3fe90b5281ce13c005ff378

**Comment by jhaddix** [comment]
We used a "bonus" category with varying point values to do some of this. We awarded bonuses for "wrote custom tooling", "newbie to CTF", and "teamup with a non-tech person". =)
