### ISSUE TITLE
Keeping the challenges page locked until CTF start time

### ISSUE THREAD

**Issue by delta24** [isislab/CTFd#86]
Hi, I gave the CTF start and end times in the config but it still shows the challenges to a non-admin user/team before the actual start time. 
Is there any functionality for this?

**Comment by delta24** [comment]
Ok, to implement this, this piece of code should be added in `challenges.py`:

```
@challenges.route('/challenges', methods=['GET'])
def challenges_view():
    if not is_admin():
        if not ctftime():
            if view_after_ctf():
                pass
            else:
                return redirect('/')
        else:
            return redirect('/news') <--- **HERE**
    if can_view_challenges():
        return render_template('chals.html', ctftime=ctftime())
    else:
        return redirect(url_for('auth.login', next='challenges'))
```

**Comment by ColdHeat** [comment]
I'm unable to replicate and your code really just prevents people from viewing challenges...

You enter in times as a UTC Timestamp. It is slightly confusing but I haven't gotten to improving how the dates are loaded. Can you tell me what times you're entering?

**Comment by delta24** [comment]
Ah, okay I must've entered the wrong dates.
