### ISSUE TITLE
Cannot create/view/edit/delete challenges in /admin/chals on latest update

### ISSUE THREAD

**Issue by delta24** [isislab/CTFd#87]
After the latest update (CSRF issue one), I can't create a challenge. It always outputs 403 error. 

Fix: in https://github.com/isislab/CTFd/blob/master/CTFd/templates/admin/chals.html#L25, this should be ` <input type="hidden" value="{{ nonce }}" name="nonce" id="nonce"> `. 

The corresponding form for creating a new challenge also does not have this CSRF input line.

After that, the created challenge cannot be viewed in `/admin/chals.html`

Here is the stack error:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/viyat/CTFd/CTFd/utils.py", line 170, in decorated_function
    return f(*args, **kwargs)
  File "/home/viyat/CTFd/CTFd/admin.py", line 236, in admin_chals
    'percentage_solved': (float(solve_count) / float(teams_with_points))
ZeroDivisionError: float division by zero
```

Replicate: 
 - New clone and install the required libraries.
 - Setup the CTF and login as admin
 - Create a challenge (no other teams registered)

Suprisingly the challenge does get created. But it is not shown in the `/admin/chals/` page.

**Comment by ColdHeat** [comment]
Finally you have a reproduceable issue. Thanks for the heads up. 

Your fix is actually incorrect and it's also unlikely that the challenge would be created in vanilla CTFd.

**Comment by delta24** [comment]
Still I cannot see any challenges to modify/delete in route `admin/chals` . There is a table 

```
            <table id='challenges'>
            </table>
```
but it does not get populated due to the stack trace I gave above. So you cannot even modify/delete/view challenges in `admin/chals/` route.

**Comment by ColdHeat** [comment]
I see your point. I will fix that later today.

**Comment by jhaddix** [comment]
Using the default install with Flask, I can confirm that after a challenge is created it does not show up in the admin view of the challenges, and therefore is not editable. 

Screenshot: https://dl.dropboxusercontent.com/u/37776965/2016-02-08_11-58-25.png

**Comment by delta24** [comment]
@ColdHeat No worries. BTW thanks for the patience and the bug fixing! I am conducting a small intra-university CTF and this was a lifesaver ;)

**Comment by ColdHeat** [comment]
@delta24 Thanks! 

This raises a general issue of admins being factored into calculations and being shown in solve counts. I'll resolve those today as well.
