### ISSUE TITLE
Admin control of teams

### ISSUE THREAD

**Issue by p4tchw0rk** [isislab/CTFd#9]
It would be nice to have more control over the teams as the admin user. There doesn't appear to be a streamlined way to remove teams from the scoreboard or start/stop self-registration.

**Comment by ColdHeat** [comment]
Removing teams from the scoreboard is implemented as a ban. Bans hide the team from the scoreboard. I don't really believe in outright banning users as I think they should be able to learn from the challenges. 

I'm not sure what you mean by start/stop self-registration? As in prevent registration until it's allowed?

**Comment by p4tchw0rk** [comment]
I'd like to be able to set up teams ahead of time and not allow any self-registration. 

Also, having the option to ban is good, but it would be nice to be able to remove teams from the game entirely (test accounts, mispelled names, etc), if that makes sense.

**Comment by ColdHeat** [comment]
I'm not sure setting up teams ahead of time applies to too many people but because I have a use case I'll implement it. 

And I'll add in user editing and team deletion.

**Comment by ColdHeat** [comment]
Going to leave this as disallowing registration and editing users. Couldn't think of a good reason to support this from the web UI when it's so much easier to script. Comming coming in a second, train wifi :(
