### ISSUE TITLE
An easy question?

### ISSUE THREAD

**Issue by tomyxy** [isislab/CTFd#92]
How to change logo.png to my personal picture?

**Comment by ColdHeat** [comment]
Well if you want to change the image itself, you can change the file here: CTFd/static/img/logo.png. But it's easier to simply edit the HTML of the index page by logging in as an admin and then going to /admin/pages or clicking the Pages link at the top of the nav bar.

**Comment by tomyxy** [comment]
i have changed CTFd/static/img/logo.png , but my index logo haven't changed.It is also the old logo

**Comment by ColdHeat** [comment]
It could be because the image is cached. Can you try using a different browser or pressing Ctrl/Cmd+ Shift+ R.

**Comment by tomyxy** [comment]
I have tried anothor browser and pressing Ctrl/Cmd+ Shift+ R , but it didn't work. And when I edit index.html  <img class="logo" src="/static/img/logo.png" /> it just can't display the picture anymore? (or i'd want to ask if there's something wrong with gunicorn?)

**Comment by ColdHeat** [comment]
I doubt there's anything wrong with gunicorn. Can you show me what text you're putting in the index route?

**Comment by tomyxy** [comment]
`<div class="row">
    <img class="logo" src="/static/img/logo.png" />
    <h2 class="text-center">
        Welcome to 2016FirstBloodCTF !
    </h2>
  <br>
    <h4 class="text-center">
      <a href="/login">Click here</a> to login and start your CTF
    </h4>
    </div>`

And page info said http://0.0.0.0:8000/static/img/logo.png :Location:http://0.0.0.0:8000/static/img/logo.png  Type:text/html Size:Unknown(not cached) Dimensions:0px * 0px(scaled to 24px *24px)

**Comment by ColdHeat** [comment]
You have updated the image in the `/CTFd/static/img` directory yes?

**Comment by tomyxy** [comment]
Yes,first time I updated with my file,it doesn't work. So then I changed back to the old logo,it is still like this

**Comment by ColdHeat** [comment]
In that case I don't know what could be causing your issue. Maybe if you can give me some more information I can give you some more suggestions but I use gunicorn to host images all the time.

**Comment by tomyxy** [comment]
I used serve.py , it  also co not load the picture ,and when i open 0.0.0.0:4000/static/img/1.jpg：
UnicodeDecodeError

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)
Traceback (most recent call last)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1836, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1820, in wsgi_app

    response = self.make_response(self.handle_exception(e))

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1403, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/helpers.py", line 822, in send_static_file

    cache_timeout=cache_timeout)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/helpers.py", line 612, in send_from_directory

    filename = safe_join(directory, filename)

    File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/helpers.py", line 582, in safe_join

    return os.path.join(directory, filename)

    File "/usr/lib/python2.7/posixpath.py", line 80, in join

    path += '/' + b

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 11: ordinal not in range(128)

**Comment by tomyxy** [comment]
I reinstalled the ctfd, and i found that when i change other files the logi can't be displayed.Only if I use source logo can it load. Is there any settings with picture (for example file size or something else)?

**Comment by tomyxy** [comment]
what's more,I have found a problem.i put filefold on desktop,and there is no db file .And when i put it into /var/www/  i found it that the logo can be changed then.but i don't known why

**Comment by Abraxas3d** [comment]
Same or similar problem here. 

Changed icon by copying new image to icon.png. Icon didn't change. 

Changed icon by editing the page source in the admin panel. Broken icon.

**Comment by ColdHeat** [comment]
There is no file called icon.png in the CTFd repo. 

What file are you referring to? logo.png? 

If you replace the file, it should change but your browser may have cached the file. If you change the source, perhaps you are referring to the incorrect location? 

It's very difficult to debug this without providing the values of anything you've changed.

**Comment by Abraxas3d** [comment]
Yes, sorry for the typo. logo.png. 

This is a very, very simple change that shouldn't fail like this, unless I'm missing something obvious. 

I found the logo.png in both the source code and in the directory structure, as described above. 

There is probably not a caching problem here, as I have now tried 5 different computers on three ISPs in two different states to check this server.  I really do know how to refresh a web browser, and have done this multiple times. 

Is a restart necessary? Is there some other mechanism with docker that won't show an image? The page source points to the right file. The file is visible in a browser on the local machine. I re-edited the new logo twice now, just in case photoshop decided to develop strong AI and stab me in the back.

**Comment by ColdHeat** [comment]
A restart shouldn't be necessary but it could fix the problem. 

I just modified the logo on the [demo CTFd instance](https://demo.ctfd.io/) to the older logo and it updated just fine. 

I think you are directing your browser to the wrong location. Unless you did something else recently like update the repo or something like that.

**Comment by ColdHeat** [comment]
Because you said Docker, are you trying to run CTFd in a docker container but modifying the content on the host OS? 

CTFd copies itself into the docker container so modifying content on the host won't do anything. 

If you are running CTFd in a container you need to use the Media Library to upload your content.

**Comment by Abraxas3d** [comment]
Media library works. It inserted a very long seemingly random named directory link. I'm having flashbacks to coding on Geocities. Let's declare victory!

**Comment by huornlmj** [comment]
> Because you said Docker, are you trying to run CTFd in a docker container but modifying the content on the host OS?
> 
> CTFd copies itself into the docker container so modifying content on the host won't do anything.
> 
> If you are running CTFd in a container you need to use the Media Library to upload your content.

Where is the Media Library?  Is it a function or feature in CTFd?
