### ISSUE TITLE
Page editor junkifies unicode characters

### ISSUE THREAD

**Issue by dwendt** [isislab/CTFd#95]
For example if attempting to paste █ into the HTML, it will be converted to a ? when the server saves it. Unsure if it's the editor or server's fault atm.

**Comment by ColdHeat** [comment]
I think this is related to the server more than the editor because it does work for me: 
https://github.com/isislab/CTFd/issues/47

**Comment by ColdHeat** [comment]
![image](https://cloud.githubusercontent.com/assets/166333/13159728/64f9097e-d661-11e5-9da8-7c27204d96cc.png)

Tried this on demo.ctfd.io.

On ctfd.io I deploy with an nginx front end that proxies to gunicorn.

**Comment by dwendt** [comment]
What's the reference locale?

:~/CTFd/CTFd$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=

**Comment by ColdHeat** [comment]
As we discussed on IRC, this is likely due to models.py using the TEXT type instead of the UNICODE type.

**Comment by dwendt** [comment]
So, when setting CTFd up with MySQL you probably want to do:

```
alter database ctfd character set utf8 collate utf8_unicode_ci;
use ctfd;
alter table challenges convert to character set utf8 collate utf8_unicode_ci;
alter table pages convert to character set utf8 collate utf8_unicode_ci;
alter table config convert to character set utf8 collate utf8_unicode_ci;
alter table files convert to character set utf8 collate utf8_unicode_ci;
alter table solves convert to character set utf8 collate utf8_unicode_ci;
alter table tags convert to character set utf8 collate utf8_unicode_ci;
alter table teams convert to character set utf8 collate utf8_unicode_ci;
alter table tracking convert to character set utf8 collate utf8_unicode_ci;
```

and in /etc/mysql/my.cnf ensure this exists...
```
[mysqld]
default-character-set=utf8
default-collation=utf8_general_ci
character-set-server=utf8
collation-server=utf8_general_ci
init-connect='SET NAMES utf8'
```
