### ISSUE TITLE
Flask Session Problem

### ISSUE THREAD

**Issue by Wdeil** [isislab/CTFd#97]
[https://pythonhosted.org/Flask-Session/](https://pythonhosted.org/Flask-Session/)

> The maximum number of items the session stores before it starts deleting some, default 500

This number is too small for some events. Maybe, you should add `SESSION_FILE_THRESHOLD = 500` in config.py, and the user can define by themselves.

**Comment by ColdHeat** [comment]
Hmm. Perhaps it's worth it to just put sessions in the database with the SqlAlchemySessionInterface

**Comment by ColdHeat** [comment]
Actually going through this CTFd hasn't actually been using Flask-Session since October. It's still in source but commented out. 

Perhaps a better issue is to reimplement it to store sessions in the database.
